[2024-02-22T18:39:34.608+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.extract_csv_data manual__2024-02-22T18:39:30.712532+00:00 [queued]>
[2024-02-22T18:39:34.615+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.extract_csv_data manual__2024-02-22T18:39:30.712532+00:00 [queued]>
[2024-02-22T18:39:34.616+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T18:39:34.628+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_csv_data> on 2024-02-22 18:39:30.712532+00:00
[2024-02-22T18:39:34.633+0000] {standard_task_runner.py:60} INFO - Started process 1178 to run task
[2024-02-22T18:39:34.636+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'extract_csv_data', 'manual__2024-02-22T18:39:30.712532+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/api_dag.py', '--cfg-path', '/tmp/tmp_ekpvdfy']
[2024-02-22T18:39:34.637+0000] {standard_task_runner.py:88} INFO - Job 241: Subtask extract_csv_data
[2024-02-22T18:39:34.675+0000] {task_command.py:423} INFO - Running <TaskInstance: api_dag.extract_csv_data manual__2024-02-22T18:39:30.712532+00:00 [running]> on host 614a08523528
[2024-02-22T18:39:34.742+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_dag' AIRFLOW_CTX_TASK_ID='extract_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T18:39:30.712532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T18:39:30.712532+00:00'
[2024-02-22T18:39:34.744+0000] {logging_mixin.py:188} INFO - Il file /home/angelica_linux/project2/***-docker/files/record_italia.csv non esiste.
[2024-02-22T18:39:34.744+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-22T18:39:34.751+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=extract_csv_data, execution_date=20240222T183930, start_date=20240222T183934, end_date=20240222T183934
[2024-02-22T18:39:34.768+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-22T18:39:34.786+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
