[2024-02-18T18:34:31.374+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.transform_data_task manual__2024-02-18T18:34:26.706854+00:00 [queued]>
[2024-02-18T18:34:31.383+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.transform_data_task manual__2024-02-18T18:34:26.706854+00:00 [queued]>
[2024-02-18T18:34:31.384+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-18T18:34:31.396+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-02-18 18:34:26.706854+00:00
[2024-02-18T18:34:31.401+0000] {standard_task_runner.py:60} INFO - Started process 3138 to run task
[2024-02-18T18:34:31.405+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'transform_data_task', 'manual__2024-02-18T18:34:26.706854+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/api_dag.py', '--cfg-path', '/tmp/tmpnxm9qm_s']
[2024-02-18T18:34:31.406+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask transform_data_task
[2024-02-18T18:34:31.454+0000] {task_command.py:423} INFO - Running <TaskInstance: api_dag.transform_data_task manual__2024-02-18T18:34:26.706854+00:00 [running]> on host 482b276ff4ae
[2024-02-18T18:34:31.535+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_dag' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T18:34:26.706854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T18:34:26.706854+00:00'
[2024-02-18T18:34:31.562+0000] {python.py:201} INFO - Done. Returned value was: [{'id': 45499}]
[2024-02-18T18:34:31.582+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=transform_data_task, execution_date=20240218T183426, start_date=20240218T183431, end_date=20240218T183431
[2024-02-18T18:34:31.657+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-18T18:34:31.680+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
